# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Sales Pop Timo"
client_id = "0808768c4fac3e254b0d1a4fa14e8ef9"
application_url = "https://objectives-subjective-deferred-twice.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://objectives-subjective-deferred-twice.trycloudflare.com/auth/shopify/callback",
  "https://objectives-subjective-deferred-twice.trycloudflare.com/authSa/shopify/callback",
  "https://objectives-subjective-deferred-twice.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hieutimonew.myshopify.com"
